// admin/src/components/general/loading-bar/loading-bar.vue
<template lang="pug">
    transition(name="fade")
        div(:class="prefixClass", :style="outerStyle", v-show="show")
            div(:class="innerClass", :style="styles")
</template>

<script>
    const prefix = `loading-bar`
    export default {
        name: 'loading-bar',
        data(){
          return {
              show:false,
              percent:0,
              status:'success'
          }
        },
        computed:{
            prefixClass(){
              return prefix
            },
            innerClass(){
                return [
                    `${this.prefixClass}-inner`,
                    {
                        [`${this.prefixClass}-inner-color-primary`]:this.color === 'primary' && this.status === 'success',
                        [`${this.prefixClass}-inner-failed-color-error`]:this.failedColor === 'error' && this.status === 'error',
                    }
                ]
            },
            outerStyle(){
              return {
                  height :`${this.height}px`
              }
            },
            styles(){
                const style = {
                    width :`${this.percent}%`,
                    height:`${this.height}px`
                }
                if (this.color !== 'primary' && this.status === 'success'){
                    style.backgroundColor = this.color
                }
                if (this.failedColor !== 'error' && this.status === 'error'){
                    style.backgroundColor = this.failedColor
                }

                return style
            }
        },
        props:{
            color:{
                type: String,
                default: 'primary'
            },
            failedColor:{
                type:String,
                default:'error'
            },
            height:{
                type:Number,
                default:2
            }
        }
    }
</script>

<style lang="stylus" scoped>
    .loading-bar
        width 100%
        position fixed
        top 0
        left 0
        right 0
        z-index 2000
        &-inner
            transition width .2s linear
            &-color-primary
                background-color #2d8cf0
            &-failed-color-error
                background-color #ed3f14
</style>

// client/src/components/common/loading-bar/loading-bar.jsx
import React from 'react'
import PropTypes from 'prop-types'

import style from './index.styl'

export default class LoadingBar extends React.Component {
    constructor() {
        super(...arguments)
        this.state = {
            show: true,
            percent: 0,
            status: 'success'
        }
    }

    static propTypes = {
        color: PropTypes.string,
        failedColor: PropTypes.string,
        height: PropTypes.number
    }

    static defaultProps = {
        height: 2,
        color:"primary",
        failedColor:"error"
    }

    static prefixCls = "loading-bar"

    getClasses() {
        let classes = []
        if (this.state.status === 'success' && this.props.color === 'primary') {
            classes = classes.concat(`${LoadingBar.prefixCls}-inner-color-primary`)
        }
        if (this.state.status === 'error' && this.props.failedColor === 'error') {
            classes = classes.concat(`${LoadingBar.prefixCls}-inner-failed-color-error`)
        }
        const _classes = classes.map(val => style[val])
        return _classes.join(' ')
    }


    getStyle() {
        const _style = {
            width: `${this.state.percent}%`,
            height: `${this.props.height}px`
        }
        if (this.state.color !== 'primary' && this.state.status === 'success') {
            _style.backgroundColor = this.props.color
        }
        if (this.state.failedColor !== 'error' && this.state.status === 'error') {
            _style.backgroundColor = this.props.failedColor
        }
        return _style
    }


    render() {
        return (
            <div ref={ref => this.self = ref} className={"hey"}>
                {this.state.show ?
                    <div className={style[LoadingBar.prefixCls]} style={{height: `${this.props.height}px`}}>
                        <div
                            className={`${style["loading-bar-inner"]} ${this.getClasses()}`}
                            style={this.getStyle()}
                        />
                    </div>
                    :
                    null
                }
            </div>
        )
    }
}
